http:
  routers:
    https-redirect:
      rule: 'HostRegexp(`{any:.*}`)'
      tls:
        options: default
        certResolver: defaultresolver
      middlewares:
      - secured
      service: redirect-all
  
  middlewares:
    secured:
      chain:
        middlewares:
        - https-redirect
        - security
    https-redirect:
      redirectScheme:
        scheme: https
    security:
      headers:
        accessControlAllowMethod:
        - GET
        - OPTIONS
        - PUT
        accessControlAllowOrigin: "origin-list-or-null"
        accessControlMaxAge: 100
        #addVaryHeader: true
        #Security
        BrowserXssFilter: true
        ContentTypeNosniff: true
        ForceSTSHeader: true
        FrameDeny: true
        SSLRedirect: true
        STSIncludeSubdomains: true
        STSSeconds: 300
        #STSPreload = true
        ContentSecurityPolicy: "default-src 'self' 'unsafe-inline'"
        CustomFrameOptionsValue: "SAMEORIGIN"
        ReferrerPolicy: "same-origin"
        FeaturePolicy: "vibrate 'self'"
                
  services:
    redirect-all:
      loadBalancer:
        servers:
         - url: ""

tls:
  options:
    default:
      sniStrict: true
      minVersion: VersionTLS12
      cipherSuites:
      - TLS_AES_128_GCM_SHA256
      - TLS_AES_256_GCM_SHA384
      - TLS_CHACHA20_POLY1305_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256          
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
      - TLS_FALLBACK_SCSV
