entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"

providers:
  docker:
    endpoint: "tcp://dockersocket:2375"
    exposedByDefault: false
    watch : true
  file:
    directory: /etc/traefik/dynamic
    watch: true
    filename: dynamic.yml

certificatesResolvers:
  defaultresolver:
    acme:
      email: $yourmailhere
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
